SurveyCreator/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/contact_us'

  get 'home/contact'

  get 'home/us'

  resources :results
  resources :answers
  
  resources :surveys do
    resources :questions
  end

   root 'pages#home'

end

SurveyCreator/app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey
end

SurveyCreator/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
  end

  # GET /questions/new
  def new
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.build
  end

  # GET /questions/1/edit
  def edit
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to [@question.survey,@question], notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: [@question.survey,@question] }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])

    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to [@question.survey,@question], notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: [@question.survey,@question] }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.destroy
    respond_to do |format|
      format.html { redirect_to survey_questions_path(@survey), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :survey_id)
    end
end

SurveyCreator/app/helpers/questions_helper.rb
module QuestionsHelper
end

SurveyCreator/app/views/questions/_form.html.erb
<%= form_for([@question.survey, @question]) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SurveyCreator/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', survey_question_path(@survey,@question) %> |
<%= link_to 'Back', survey_questions_path(@survey) %>

SurveyCreator/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question.each do |question| %>
      <tr>
        <td><%= question.question %></td>
        <td><%= link_to 'Show', survey_question_path(@survey, question) %></td>
        <td><%= link_to 'Edit', edit_survey_question_path(@survey, question) %></td>
        <td><%= link_to 'Destroy', survey_question_path(@survey, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_survey_question_path %>

SurveyCreator/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_questions_path %>

SurveyCreator/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_survey_question_path(@survey, @question) %> |
<%= link_to 'Back', survey_questions_path %>